version: '3.9'
services:
  hasura:
    image: hasura/graphql-engine:latest
    ports:
      - "8080:8080"
    restart: always
    container_name: hasura
    environment:
      HASURA_GRAPHQL_DATABASE_URL: 
      HASURA_GRAPHQL_ENABLE_CONSOLE: 
      HASURA_GRAPHQL_DEV_MODE: 
      HASURA_GRAPHQL_ADMIN_SECRET:
